import html

def _list_items(items):
   if not items:
       return "<li>None</li>"
   return "".join(f"<li>{html.escape(str(item))}</li>" for item in items)


def build_capstone_html(summary: dict) -> str:
   stories_count = summary.get("stories_count", 0)
   tasks_count = summary.get("tasks_count", 0)
   code_count = summary.get("code_count", 0)
   tests_count = summary.get("tests_count", 0)
   integration_count = summary.get("integration_count", 0)
   governance_count = summary.get("governance_count", 0)
   allowed_count = summary.get("governance_allowed_count", 0)
   blocked_count = summary.get("governance_blocked_count", 0)

   sample_story_titles = summary.get("sample_story_titles", [])
   sample_tasks = summary.get("sample_tasks", [])
   sample_integration_targets = summary.get("sample_integration_targets", [])
   sample_governance_issues = summary.get("sample_governance_issues", [])

   return f"""<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <title>AI Product Builder Capstone Output</title>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <style>
   body {{
     font-family: Arial, sans-serif;
     margin: 40px;
     line-height: 1.5;
     background: #f7f7f7;
     color: #222;
   }}
   .container {{
     max-width: 1000px;
     margin: 0 auto;
     background: white;
     padding: 32px;
     border-radius: 12px;
     box-shadow: 0 2px 12px rgba(0,0,0,0.08);
   }}
   h1, h2 {{
     margin-top: 0;
   }}
   .grid {{
     display: grid;
     grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
     gap: 16px;
     margin: 24px 0;
   }}
   .card {{
     border: 1px solid #ddd;
     border-radius: 10px;
     padding: 16px;
     background: #fafafa;
   }}
   .label {{
     font-size: 14px;
     color: #666;
   }}
   .value {{
     font-size: 28px;
     font-weight: bold;
     margin-top: 8px;
   }}
   ul {{
     padding-left: 20px;
   }}
   code {{
     background: #f1f1f1;
     padding: 2px 6px;
     border-radius: 4px;
   }}
 </style>
</head>
<body>
 <div class="container">
   <h1>AI Product Builder - Final Capstone Output</h1>
   <p>This page was generated by the Day 15 capstone system and summarizes the full governed pipeline run.</p>

   <div class="grid">
     <div class="card"><div class="label">Stories</div><div class="value">{stories_count}</div></div>
     <div class="card"><div class="label">Tasks</div><div class="value">{tasks_count}</div></div>
     <div class="card"><div class="label">Code Objects</div><div class="value">{code_count}</div></div>
     <div class="card"><div class="label">Tests</div><div class="value">{tests_count}</div></div>
     <div class="card"><div class="label">Integration Results</div><div class="value">{integration_count}</div></div>
     <div class="card"><div class="label">Governed Results</div><div class="value">{governance_count}</div></div>
     <div class="card"><div class="label">Allowed Records</div><div class="value">{allowed_count}</div></div>
     <div class="card"><div class="label">Blocked Records</div><div class="value">{blocked_count}</div></div>
   </div>

   <h2>Sample Story Titles</h2>
   <ul>{_list_items(sample_story_titles)}</ul>

   <h2>Sample Tasks</h2>
   <ul>{_list_items(sample_tasks)}</ul>

   <h2>Sample Integration Targets</h2>
   <ul>{_list_items(sample_integration_targets)}</ul>

   <h2>Sample Governance Issues</h2>
   <ul>{_list_items(sample_governance_issues)}</ul>

   <h2>Next Step</h2>
   <p>Open this file in a browser or serve it locally with <code>python -m http.server 8000</code> and visit <code>http://localhost:8000/day-15-capstone/capstone_output.html</code>.</p>
 </div>
</body>
</html>
"""
